# Generated by Django 2.2.6 on 2019-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('arabic_text', models.TextField()),
                ('urdu_text', models.TextField()),
                ('english_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('arabic_text', models.TextField()),
                ('urdu_text', models.TextField()),
                ('english_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('arabic_hadees', models.TextField()),
                ('urdu_hadees', models.TextField()),
                ('english_hadees', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hadees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('arabic_text', models.TextField()),
                ('urdu_text', models.TextField()),
                ('english_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IftarHadees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('iftar_hadees', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LailaTulQadarHadees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('laila_tul_qadar_hadees', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic', models.TextField()),
                ('urdu_arabic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RamzanHadees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('ramzan_hadees', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SehrHadees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('sehr_hadees', models.TextField()),
            ],
        ),
    ]
