# Generated by Django 2.2.6 on 2019-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iftarhadees',
            name='iftar_hadees',
        ),
        migrations.RemoveField(
            model_name='lailatulqadarhadees',
            name='laila_tul_qadar_hadees',
        ),
        migrations.RemoveField(
            model_name='ramzanhadees',
            name='ramzan_hadees',
        ),
        migrations.RemoveField(
            model_name='sehrhadees',
            name='sehr_hadees',
        ),
        migrations.AddField(
            model_name='iftarhadees',
            name='arabic_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='iftarhadees',
            name='english_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='iftarhadees',
            name='urdu_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lailatulqadarhadees',
            name='arabic_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lailatulqadarhadees',
            name='english_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lailatulqadarhadees',
            name='urdu_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ramzanhadees',
            name='arabic_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ramzanhadees',
            name='english_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ramzanhadees',
            name='urdu_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sehrhadees',
            name='arabic_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sehrhadees',
            name='english_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sehrhadees',
            name='urdu_text',
            field=models.TextField(default=''),
        ),
    ]
