# Generated by Django 2.2.6 on 2019-11-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191120_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eid',
            name='arabic_hadees',
        ),
        migrations.RemoveField(
            model_name='eid',
            name='english_hadees',
        ),
        migrations.RemoveField(
            model_name='eid',
            name='urdu_hadees',
        ),
        migrations.AddField(
            model_name='eid',
            name='arabic_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eid',
            name='english_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eid',
            name='urdu_text',
            field=models.TextField(default=''),
        ),
    ]
